### ISSUE TITLE
It seems that is not tracking gtag('set', params);

### ISSUE THREAD

**Issue by BruneXX** [codediodeio/angular-gtag#18]
I've tried to use **set()** method and debugging with GA debug extension for chrome with no success, the set() method doesn't set anything.

code was:
`this.gtag.set({ user_id: this.userId });`

**Comment by BruneXX** [comment]
I think I know where the issue is, I'll make a PR soon.

**Comment by StarWix** [comment]
Fixed in https://github.com/codediodeio/angular-gtag/pull/15

**Comment by rivanitskiy** [comment]
This fix is still not in the master. When are you going to publish it?

**Comment by PixelPerfectJenna** [comment]
@StarWix fix still doesn't seem to be implemented. @codediodeio is there a problem with the PR?
